name: myapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.4.0 # Tambahkan baris ini untuk menggunakan ikon FontAwesome
  pin_code_fields: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Contoh untuk menambahkan assets, sesuaikan dengan kebutuhan proyek Anda.
  assets:
    - assets/logoscin.png
    - assets/community.png
    - assets/scan.jpg
    - assets/skinface.jpg
  #   - assets/logo.png
  #   - assets/other_image.png

  # Contoh untuk menambahkan custom fonts, sesuaikan dengan kebutuhan proyek Anda.
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
